//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int ID { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public System.DateTime AssignDate { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Item Item { get; set; }
    }
}
