//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Assignments = new HashSet<Assignment>();
        }
    
        public int ID { get; set; }
        public string SerialNumber { get; set; }
        public string ItemModel { get; set; }
        public string ScreenSize { get; set; }
        public string Processor { get; set; }
        public string HDD { get; set; }
        public string Memory { get; set; }
        public string OperatingSystem { get; set; }
        public Nullable<int> Brand { get; set; }
        public Nullable<int> Supplier { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Connectivity { get; set; }
        public System.DateTime WarrantyExpire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual Brand Brand1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Connectivity Connectivity1 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Supplier Supplier1 { get; set; }
    }
}
